name : Mediplus Website Docker Build
on:
  push:
    branches:
      - main

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and push Docker image
      run: |
        docker build -t mediplus-website:${{ github.sha }} .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag mediplus-website:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/mediplus-website:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mediplus-website:latest
        docker tag mediplus-website:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/mediplus-website:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/mediplus-website:${{ github.sha }}